LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;
USE IEEE.NUMERIC_STD.ALL;
ENTITY MIDDLE_XOR IS PORT
(
V0_IN :IN STD_LOGIC_VECTOR (63 DOWNTO 0);
V3_IN :IN STD_LOGIC_VECTOR (63 DOWNTO 0);
MESSAGE_0 :IN STD_LOGIC_VECTOR (63 DOWNTO 0);
MESSAGE_1 :IN STD_LOGIC_VECTOR (63 DOWNTO 0);
V0_OUT :OUT STD_LOGIC_VECTOR(63 DOWNTO 0);
V3_OUT :OUT STD_LOGIC_VECTOR(63 DOWNTO 0)
);
END MIDDLE_XOR;
ARCHITECTURE ARCH_MIDDLE_XOR OF MIDDLE_XOR IS
BEGIN
V0_OUT <= V0_IN XOR MESSAGE_0;
V3_OUT <= V3_IN XOR MESSAGE_1;
END ARCHITECTURE;